
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND BUFFER COMMA FALSE ID LARROW NAND NOR NOT OR RARROW SEMICOLON TRUE VALUE XNOR XOR\n    program : sentences\n    sentences : sentences sentence\n                | sentence\n    sentence : expression SEMICOLON\n    expression : TRUE\n                | FALSE\n    \n    expression : AND LARROW expression COMMA expression RARROW \n                | OR LARROW expression COMMA expression RARROW \n                | NOT LARROW expression RARROW \n                | XOR LARROW expression COMMA expression RARROW \n                | BUFFER LARROW expression RARROW \n                | NAND LARROW expression COMMA expression RARROW \n                | NOR LARROW expression COMMA expression RARROW \n                | XNOR LARROW expression COMMA expression RARROW \n    '
    
_lr_action_items = {'TRUE':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[5,5,-3,-2,-4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,]),'FALSE':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[6,6,-3,-2,-4,6,6,6,6,6,6,6,6,6,6,6,6,6,6,]),'AND':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[7,7,-3,-2,-4,7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'OR':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[8,8,-3,-2,-4,8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'NOT':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[9,9,-3,-2,-4,9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'XOR':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[10,10,-3,-2,-4,10,10,10,10,10,10,10,10,10,10,10,10,10,10,]),'BUFFER':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[11,11,-3,-2,-4,11,11,11,11,11,11,11,11,11,11,11,11,11,11,]),'NAND':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[12,12,-3,-2,-4,12,12,12,12,12,12,12,12,12,12,12,12,12,12,]),'NOR':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[13,13,-3,-2,-4,13,13,13,13,13,13,13,13,13,13,13,13,13,13,]),'XNOR':([0,2,3,15,16,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[14,14,-3,-2,-4,14,14,14,14,14,14,14,14,14,14,14,14,14,14,]),'$end':([1,2,3,15,16,],[0,-1,-3,-2,-4,]),'SEMICOLON':([4,5,6,35,37,47,48,49,50,51,52,],[16,-5,-6,-9,-11,-7,-8,-10,-12,-13,-14,]),'COMMA':([5,6,25,26,28,30,31,32,35,37,47,48,49,50,51,52,],[-5,-6,33,34,36,38,39,40,-9,-11,-7,-8,-10,-12,-13,-14,]),'RARROW':([5,6,27,29,35,37,41,42,43,44,45,46,47,48,49,50,51,52,],[-5,-6,35,37,-9,-11,47,48,49,50,51,52,-7,-8,-10,-12,-13,-14,]),'LARROW':([7,8,9,10,11,12,13,14,],[17,18,19,20,21,22,23,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'sentences':([0,],[2,]),'sentence':([0,2,],[3,15,]),'expression':([0,2,17,18,19,20,21,22,23,24,33,34,36,38,39,40,],[4,4,25,26,27,28,29,30,31,32,41,42,43,44,45,46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> sentences','program',1,'p_program','parser.py',5),
  ('sentences -> sentences sentence','sentences',2,'p_sentences','parser.py',9),
  ('sentences -> sentence','sentences',1,'p_sentences','parser.py',10),
  ('sentence -> expression SEMICOLON','sentence',2,'p_sentence','parser.py',14),
  ('expression -> TRUE','expression',1,'p_expression_value','parser.py',18),
  ('expression -> FALSE','expression',1,'p_expression_value','parser.py',19),
  ('expression -> AND LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',25),
  ('expression -> OR LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',26),
  ('expression -> NOT LARROW expression RARROW','expression',4,'p_expresion','parser.py',27),
  ('expression -> XOR LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',28),
  ('expression -> BUFFER LARROW expression RARROW','expression',4,'p_expresion','parser.py',29),
  ('expression -> NAND LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',30),
  ('expression -> NOR LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',31),
  ('expression -> XNOR LARROW expression COMMA expression RARROW','expression',6,'p_expresion','parser.py',32),
]
